### ISSUE TITLE
Generar abstract y TOC

### ISSUE THREAD

**Issue by darlu-es** [darlu-es/darlu#17]
Basándonos en este ejemplo: file:///home/i3wm/proyectos%20(copy%201)/darlu/doc/markdeep_example.html

![image](https://user-images.githubusercontent.com/36248806/89551159-e87cff80-d80a-11ea-91ce-d422fc192913.png)

Como 75% y 25% respectivamente? En el print no deben aparecer o hacerlos estéticos.

El código se haría con

``` html
<div class="abstract">
  <h2>Abstract</h2>
  <p>...</p>
</div>
```
Sustituyendo abstract y toc respectivamente.

CSS mediumTOC

``` css
/* if screen is wide enough, put table of contents on the right side */
@media screen and (min-width: 60em) {
	.md .longTOC, .md .mediumTOC, .md .shortTOC {
		max-width: 20%;
		width: 20%;
		float: right;
		position: fixed;
		right: 0px;
		top: 0px;
	}
}
/* for narrow screens or print, hide table of contents */
@media screen and (max-width: 60em) {
	.md .longTOC, .md .mediumTOC, .md .shortTOC { display: none; }
	body { max-width: 100%; }
}
@media print {
	.md .longTOC, .md .mediumTOC, .md .shortTOC { display: none; }
	body { max-width: 100%; }
}
```

CSS Abstract

``` css
/* Center title and paragraph */
.abstract,
.abstract p {
  text-align: center;
  margin-top: 0;
}
.abstract {
  margin: 2.25rem 0;
}
.abstract > h2 {
  font-size: 1rem;
  margin-bottom: -0.2rem;
}
```
