### ISSUE TITLE
Libros?

### ISSUE THREAD

**Issue by darlu-es** [darlu-es/darlu#9]
https://3d-book-css.netlify.app/

``` css
.book-container {
  --rotate: -30deg;
  --rotateHover: -20deg;
  --perspective: 600px;
  --transitionDuration: 1s;
  --radius: 2px;
  --thickness: 15px;
  --bgColor: #01060f;
  --width: 200px;
}

.book-container {
  display: flex;
  justify-content: center;
  padding: 20px 30px;
}

.book-container:hover {
  --rotate: var(--rotateHover);
}

.book {
  margin-left: calc(-15px - var(--thickness));
  background: var(--bgColor);
  transform: perspective(var(--perspective)) rotateY(var(--rotate));
  transition: transform ease var(--transitionDuration);
  position: relative;
}

.book img {
  margin: 0;
  width: var(--width);
  height: auto;
  border-radius: var(--radius);
}

.book:before,
.book:after {
  position: absolute;
  top: calc(1.5% + var(--thickness) / 7.5);
  height: calc(97.5% - var(--thickness) / 2.5);
  content: ' ';
  z-index: -1;
}

.book:before {
  width: 100%;
  top: calc(2% + var(--thickness) / 7.5);
  height: calc(97.5% - var(--thickness) / 1.75);
  left: calc(var(--thickness) + 2px);
  background-color: var(--bgColor);
  box-shadow: 5px 5px 20px #333;
  border-radius: var(--radius);
}

.book:after {
  width: var(--thickness);
  left: 100%;
  background-color: #efefef;
  box-shadow: inset 0px 0px 5px #aaa;
  transform: perspective(100px) rotateY(20deg);
}
```

``` html
<a 
  class="book-container"
  href="https://leanpub.com/outstanding-developer"
  target="_blank"
  rel="noreferrer noopener"
>
  <div class="book">
    <img
      alt="The Outstanding Developer by Sebastien Castiel"
      src="/book-cover.76b99e5d.png"
      />
  </div>
</a>
```

https://github.com/scastiel/3d-book-image-css-generator
